### ISSUE TITLE
Generic build & run scripts

### ISSUE THREAD

**Issue by daniel-duliga** [daniel-duliga/bgt-web#73]
# Table of Contents

1.  [Generic build & run scripts <code>[100%]</code>](#org4ae3aeb)

<a id="org4ae3aeb"></a>

# TODO Generic build & run scripts <code>[100%]</code>

-   [X] Extract the actual build and run functionality from the Jenkins job into scripts
-   [X] Test Jenkins job that sets the appropriate environment variables and calls the scripts
-   [X] Make sure that the environment can be specified from outside of the scripts (environment variables)
-   [X] Make sure that the appropriate deployment is stopped after a successful build
    -   Maybe kill by port?
-   [X] Don't build if the .env<sub>live</sub> file is missing
-   [X] Commit the jobs and scripts on both `master` and `develop`
    -   will probably branch from `master`, merge back into `master` and then also merge into `develop`
-   [X] Update the Staging job and also add a new one for Production

**Comment by daniel-duliga** [comment]
# Table of Contents

1.  [Generic build & run scripts <code>[100%]</code>](#org4ae3aeb)


<a id="org4ae3aeb"></a>

# TODO Generic build & run scripts <code>[100%]</code>

-   [X] Extract the actual build and run functionality from the Jenkins job into scripts
-   [X] Test Jenkins job that sets the appropriate environment variables and calls the scripts
-   [X] Make sure that the environment can be specified from outside of the scripts (environment variables)
-   [X] Make sure that the appropriate deployment is stopped after a successful build
    -   Maybe kill by port?
-   [X] Don't build if the .env<sub>live</sub> file is missing
-   [X] Commit the jobs and scripts on both `master` and `develop`
    -   will probably branch from `master`, merge back into `master` and then also merge into `develop`
-   [X] Update the Staging job and also add a new one for Production

**Comment by daniel-duliga** [comment]
1edd21f9dde1a120bb462ae85c932574ac2e67c1
2e1ae46daf1d53732d3c4ebca53e1f7d10fc5c58
